name: Test and Merge Staged Mesa Cask

on:
  push:
    branches:
      - staged

concurrency:
  group: staged-mesa-cask
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link tap to Homebrew
        run: |
          TAP_PATH="$(brew --repository)/Library/Taps/mesa-dot-dev/homebrew-tap"
          mkdir -p "$(dirname "$TAP_PATH")"
          ln -s "$GITHUB_WORKSPACE" "$TAP_PATH"

      - name: audit brew
        run: brew audit --strict --new mesa-dot-dev/tap/mesa

      - name: audit brew style
        run: brew style Casks/mesa.rb

      - name: confirm brew installation works
        run: brew install --cask mesa-dot-dev/tap/mesa

  merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge staged into main
        run: |
          git config user.name "mesa-ci[bot]"
          git config user.email "ci-bot@mesa.dev"
          git checkout main
          git merge staged --no-edit
          git push origin main

      - name: Reset staged to main
        run: git push origin main:staged --force

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.test.result == 'failure' || needs.test.result == 'timed_out' || needs.merge.result == 'failure' || needs.merge.result == 'timed_out') }}
    needs:
      - test
      - merge
    steps:
      - uses: actions/checkout@v4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: mesa-gh
          SLACK_TITLE: "Test and Merge workflow failed"
          SLACK_MESSAGE: "test: ${{ needs.test.result }}, merge: ${{ needs.merge.result }}"
          MSG_MINIMAL: actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
